# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: St. Michael Lutheran Church
street_address: 2208 Princess Anne Rd
county: Virginia Beach
state: VA
zipcode: 23456
email: church@smlvb.org
description: > # this means to ignore newlines until "baseurl:"
  St. Michael is a congregation of the Evangelical Lutheran Church in America.
  We were organized in 1988 and became the first congregation of the newly formed 
  ELCA in the Virginia Synod.
baseurl: "" # the subpath of your site, e.g. /blog
url: "smlvb.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  smlvborg

# Build settings
markdown: kramdown

#glynn
ftp_host: 'ftp.smlvb.org'
ftp_dir: 'www/'
ftp_passive: false

# optional
ftp_port: 22                  # default 21
ftp_username: 'smlvborg'     # default read from stdin
ftp_secure: true              # default false